[package]
name = "emacs-import-typescript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "emacs-command-import-typescript"
path = "src/main.rs"

[dependencies]
